name: Deploy
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    # TODO: is it worth using files/folders from the nuxt documentation to determine when to deploy?
    # https://v3.nuxtjs.org/guide/directory-structure/nuxt
jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15'
          cache: 'npm'

      # Look in to caching dependencies for faster consecutive runs
      # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

      # Generate static files
      - run: npm ci
      # TODO: tests
      # - run: npm run test
      - run: npm run generate

      # Deploy static site to gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          cname: stylesheet.fun
